### ISSUE TITLE
Upon initialization an error is raised regarding "grid.extendToolbar.min.js.map" 

### ISSUE THREAD

**Issue by APEXGru** [mgoricki/apex-plugin-extend-ig-toolbar#1]
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (grid.extendToolbar.min.js.map, line 0)

This happens on your demo on apex.oracle.com as well as on our local installation.

**Comment by mgoricki** [comment]
Can you try it now? It looks like problem appeared only in Safari.

**Comment by mgoricki** [comment]
It's fixed.
