### ISSUE TITLE
no such method getToolbar

### ISSUE THREAD

**Issue by mendesn** [mgoricki/apex-plugin-extend-ig-toolbar#6]
Can anyone help me with this, please?

Uncaught Error: no such method 'getToolbar' for interactiveGrid widget instance

I upload only the plug-in since we don't have permissions to put in the application server

Thanks

**Comment by mgoricki** [comment]
What's your APEX version?
Have you tried it at apex.oracle.com?

Br,
Marko

**Comment by mendesn** [comment]
my Apex version is 5.1
where can I find this method?

**Comment by mgoricki** [comment]
Did you manage to make this work?

**Comment by mgoricki** [comment]
No response.
