### ISSUE TITLE
Rows Per Page missing when using the plugin

### ISSUE THREAD

**Issue by ma-schroeder** [mgoricki/apex-plugin-extend-ig-toolbar#7]
Hello Marko,

when using the plugin to create a button in the IG-header to trigger a custom DA i realized that the Format-Option to change the rows per page disappered in the Actions-menu of the grid.

The Pagination-Type in the Grid-Attributes is set to "Page" and this is the normal behaviour **without** your plugin:

![rows-1](https://user-images.githubusercontent.com/11662301/54825665-668c4500-4cae-11e9-8c2e-ca48107f2b33.jpg)

When i add or enable the plugin it looks as follows:

![rows-2](https://user-images.githubusercontent.com/11662301/54825704-7b68d880-4cae-11e9-8771-99d71c715b2f.jpg)

The custom DA has the following options and it will trigger the Excel-Download with another plugin:

![rows-3](https://user-images.githubusercontent.com/11662301/54825822-b66b0c00-4cae-11e9-92ad-908531c5fd3a.jpg)

And here are my options of your plugin:

![rows-4](https://user-images.githubusercontent.com/11662301/54825847-c387fb00-4cae-11e9-8af8-d9aab8839ae7.jpg)

I am using APEX 18.2 but i just tested it on the APEX-website with version 19.1 and its the same problem.

Thank you

Regards,
Mathias

**Comment by mgoricki** [comment]
Hi Mathias,

sorry for the late reply. 
I'll try to check it out as soon as possible.

Br,
Marko

**Comment by ma-schroeder** [comment]
Hello Marko,

here is the sample app i created on apex.oracle.com

Workspace: MASCHROE2
User: demo
PW: demodemo

https://apex.oracle.com/pls/apex/f?p=111666:1

Thanks
Mathias

**Comment by mgoricki** [comment]
This issue has been fixed in v1.0.3 of the plugin (available for APEX 19.2.*).
Thanks for reporting this and sorry for the delay!

Br,
Marko
